### ISSUE TITLE
Layout do painel

### ISSUE THREAD

**Issue by khayo** [khayo/SMG#1]
Necessário criação de layout do painel frontal do módulo contendo os botões de comando e visor. Botões presentes:

Seta para esquerda
Seta para direita
Reset
Manual
Automático
Partir
Parar
Rede
Desliga
Gerador

Em caso de dúvida, use este espaço para tirar dúvidas, dessa forma mantemos um histórico do desenvolvimento.
Caso se interesse por esta tarefa, responda esta Issue se compromentendo com sua execução. **Informar tempo necessário para desenvolvimento da tarefa.**
O layout deve ser entregue em formato de imagem, preferencialmente PNG.
Mais de uma pessoa pode se encarregar do desenvolvimento desta tarefa, tanto como um grupo, como individualmente.

Procure outros módulos ja existentes para ter uma ideia de como fazer, alguns exemplos de modulo. AMF25, HMI2011, DSE4610, DSE7410, 

Conto com o engajamento de todos

**Comment by DovahKrosis** [comment]
Vou tentar, só não prometo um Brad Pitt ! hehe

**Comment by DovahKrosis** [comment]
tempo necessário para desenvolvimento da tarefa : 1 Hora

**Comment by khayo** [comment]
Verificar tamanho do display ks0108 para que esteja na proporção correta
centralizar botões das setas
Melhorar distribuição dos botões
Agrupar corretamente os botões
Mehorar apresentação das fontes
--
Khayo Vannucci Rodrigues
11 98111-9785


Em dom, 6 de out de 2019 às 13:23, DovahKrosis <notifications@github.com>
escreveu:

**Comment by khayo** [comment]
outros exemplos de módulo:
k30, dpc650, dkg 705

**Comment by Lucfoxxd** [comment]
Feito Layout Frontal do Módulo. Está presente na pasta Layout

**Comment by khayo** [comment]
OK @Lucfoxxd, acredito que [está seja a melhor disposição dos botões](https://github.com/khayo/SMG/blob/master/Layout/Layout_Frontal_do_Modulo_Lucas.png). Agora precisamos de uma versão **"em tamanho real"** com as medidas corretas dos botões e do display (ks0108). Vamos precisar mudar essas cores também, esse verde não está legal. Acho melhor uma cor mais neutra, tipo **cinza claro**. A cor do nosso **display é azul.** Acho que agora o Paint vai deixar a desejar, então procure alguém com **COMPROMISSO** e que vá te entregar essa tarefa **dentro do prazo** que escolheu para execução.

Caso alguém queira se encarregar dessa tarefa **até o fim**, informe o prazo necessário para **conclusão do trabalho.**

**Comment by Lucfoxxd** [comment]
**Prazo de entrega estimado: 12/10/19 (Sábado) até às 20h**

**Comment by Lucfoxxd** [comment]
Guilherme, você que tem botões, teria como me levar algum até sexta estourado?
Ou então me mandar a medida do botão que será usado no projeto (o que está na placa do layout que você executou).

**Comment by khayo** [comment]
@lucfoxxd, usa o @ pra marcar e ele receber notificação

**Comment by DovahKrosis** [comment]
levo um botão

**Comment by Lucfoxxd** [comment]
Valeu, obrigado.
@khayo 
@DovahKrosis

**Comment by Lucfoxxd** [comment]
![Layout_Frontal_do_Módulo](https://user-images.githubusercontent.com/55931764/66599187-080ab380-eb79-11e9-9ce6-3562a7516dbb.png)
Atualizado Layout Frontal do Módulo. Preciso de vocês analisem e apontem melhorias o quanto antes para que eu possa colocar as medidas reais logo.
@Premone 
@cplds 
@DovahKrosis 
@khayo

**Comment by Lucfoxxd** [comment]
![image](https://user-images.githubusercontent.com/55931764/66601502-73a34f80-eb7e-11e9-89aa-87c83e46c71f.png)
Medidas como estão por enquanto.

**Comment by Lucfoxxd** [comment]
![image](https://user-images.githubusercontent.com/55931764/66602240-16a89900-eb80-11e9-86eb-1ac19ce6c05b.png)
Atualizado Layout Frontal do Módulo. Preciso de vocês analisem e apontem melhorias o quanto antes para que eu possa colocar as medidas reais logo.
@Premone
@cplds
@DovahKrosis
@khayo

**Comment by Lucfoxxd** [comment]
![image](https://user-images.githubusercontent.com/55931764/66602496-a0586680-eb80-11e9-8065-149681b73833.png)
Medidas como estão.

**Comment by Lucfoxxd** [comment]
![image](https://user-images.githubusercontent.com/55931764/66618998-adda1480-ebb1-11e9-9d10-c28e24af66e7.png)
Atualizado Layout Frontal do Módulo. Preciso de vocês analisem o quanto antes e deem suas opiniões e veredito.
@Premone
@cplds
@DovahKrosis
@khayo

**Comment by Lucfoxxd** [comment]
![image](https://user-images.githubusercontent.com/55931764/66619197-70c25200-ebb2-11e9-84f0-6cd7f0b50037.png)
Medidas reais. Analisem um possível erro.
Obs: A imagem tipo não está proporcional às medidas.

**Comment by DovahKrosis** [comment]
10 por 15 cm só ? O case deveria ser maior que a placa, acho que pelo menos mais 5x5 maior

**Comment by Lucfoxxd** [comment]
Então. Isso vai ser embutido na maleta, pelo o que eu entendi. Não vai ser um módulo tipo aquele que o Khayo mostrou para nós.

**Comment by Lucfoxxd** [comment]
Eu também achei pequeno, seria o tamanho da placa. Mas pelo que entendi, é isso.

**Comment by Lucfoxxd** [comment]
Esperemos o que vão dizer pra finalizar essa parte e vamos ver.

**Comment by khayo** [comment]
Se esta imagem estiver com as proporções corretas, pode até mesmo diminuir a largura, pq ele está com aparência de achatado

**Comment by Lucfoxxd** [comment]
A imagem não está na proporção correta, o obs ali na foto com as medidas. Teria que colocar o display um pouco mais para baixo e diminuir bastante os botões e a parte física.

**Comment by khayo** [comment]
Aí vc me complica né jovem. Acerta essas proporções pra gente definir o que fazer

**Comment by Lucfoxxd** [comment]
Okay.

**Comment by Lucfoxxd** [comment]
Farei isso

**Comment by Lucfoxxd** [comment]
![image](https://user-images.githubusercontent.com/55931764/66693919-a2a3e900-ec84-11e9-8a58-cad23f50945b.png)
Acertado as medidas corretas e agora está proporcional. Pode conferir.
Escala em milímetros, mas, é só voltar uma casa decimal que é centímetro.
**Obs: Não dá para ver na imagem eu acho, mas, todos os botões tem 6mm ou 0,6cm de acordo com seu DataSheet.**

**Comment by DovahKrosis** [comment]
Muito bom em mano, as proporções estão legais

**Comment by Lucfoxxd** [comment]
Na outra tava bem achatado como o Khayo disse, tava sobrando espaço de mais.
As medidas estão de acordo com a metragem do CorelDraw.

**Comment by Lucfoxxd** [comment]
E aí, tá legal? Posso botar na monografia isso?

**Comment by khayo** [comment]
Pode

**Comment by Lucfoxxd** [comment]
Belezinha.

**Comment by khayo** [comment]
Layout entregue em 13/10/2019 e0d3a0bcce2aa6c535c58c9038718beaaf7c645f
