### ISSUE TITLE
Confecção de placa de rele

### ISSUE THREAD

**Issue by khayo** [khayo/SMG#2]
Necessário confecção de **UMA** placa de rele conforme projeto [anexo](http://dicasdopinguim.com.br/wp-content/uploads/2019/10/placa_rele.zip).
Informações adicionais:
- Material será fornecido e entregue ao responsavel pela confecção no dia seguinte do aceite
- A placa deve ter 25mmx30mm
- Os contato NA e NF devem ser os bornes laterais
- Placa deve ser feita com **CAPRIXO**, pois integrará o modelo apresentado na semana da ETE

Algumas imagens de referencia de como deve ser a aparência final da placa neste [link](http://dicasdopinguim.com.br/wp-content/uploads/2019/10/placa_rele.zip)

Em caso de dúvidas, pergunte por aqui, para que possamos manter o histórico do desenvolvimento

**Informar prazo necessário para confecção**

**Comment by Lucfoxxd** [comment]
Olá pessoa a qual está atribuída a tarefa. **Mande um prazo para entrega da tarefa totalmente FINALIZADA**, lembrando que **dentro desse prazo** será feita análise (todos os membros), revisão (todos os membros) e então quando aprovado, será entregue e marcada como concluída, portanto tentem não se perder na resolução da tarefa para não atrasar o desenvolvimento das outras partes que dependem desta tarefa para serem feitas.

**Qualquer dúvida, mande aqui!**

**Comment by Lucfoxxd** [comment]
@cplds

**Comment by cplds** [comment]
Tenho a placa já furada e desenhada, e vou levá-la hoje para resolver algumas considerações finais antes de corroer. Caso tudo dê certo, levarei-a montada amanhã.
