### ISSUE TITLE
Projetar teclado do módulo

### ISSUE THREAD

**Issue by khayo** [khayo/SMG#3]
Após definição do layout do painel do módulo, será necessário desenvolver o teclado.
A tarefa consiste em entregar um projeto de como deve ser o PCB do teclado

Algumas especificações

- Os **valores de resistor devem aparecer** no layout **corretamente** (consultar arquivo de projeto do proteus)
- A saída do teclado para o módulo deve **ter 3 fios**: positivo, negativo e comunicação. 
- Os materiais devem ser **especificados e levantados por você**
- **Não confeccionar placa**, somente o projetar o designe para que seja aprovado

Em caso de dúvidas, pergunte por aqui, para que possamos manter o histórico do desenvolvimento

**Informar tempo necessário para desenvolvimento da tarefa.** Lembre-se, que este prazo é para entraga da tarefa **FINALIZADA**, ou seja, após **testes**, **análise** do material entregue e **aprovação** dos membros do grupo, portanto considere estes passos para **definir o prazo** para **finalização da tarefa**

**Comment by Lucfoxxd** [comment]
Olá pessoal a qual estão atribuídos a tarefa. **Mandem um prazo para entrega da tarefa totalmente FINALIZADA**, lembrando que **dentro desse prazo** será feita análise (todos os membros), revisão (todos os membros) e então quando aprovado, será entregue e marcada como concluída, portanto tentem não se perder na resolução da tarefa para não atrasar o desenvolvimento das outras partes que dependem desta tarefa.

**Qualquer dúvida, mandem aqui!**

**Comment by DovahKrosis** [comment]
PRAZO: QUINTA-FEIRA 10hAM

**Comment by DovahKrosis** [comment]
![back](https://user-images.githubusercontent.com/55958011/66440781-9c0a3d00-ea0a-11e9-9fe2-4402ded0ab30.png)
![layout](https://user-images.githubusercontent.com/55958011/66440783-9c0a3d00-ea0a-11e9-8dba-0009ccf8f253.png)
![front](https://user-images.githubusercontent.com/55958011/66440784-9c0a3d00-ea0a-11e9-8e88-408bbb02dbe8.png)

**Comment by DovahKrosis** [comment]
Os resistores estão com os valores na placa ! Os push buttons estão com o contato cruzado.

**Comment by DovahKrosis** [comment]
![back](https://user-images.githubusercontent.com/55958011/66441674-4afc4800-ea0e-11e9-9568-38eda0a7ac28.png)
![layout](https://user-images.githubusercontent.com/55958011/66441675-4afc4800-ea0e-11e9-9d97-dda0caa0355a.png)
![front](https://user-images.githubusercontent.com/55958011/66441676-4afc4800-ea0e-11e9-97ae-13a6d94e487b.png)

Atualização Layout 1

**Comment by DovahKrosis** [comment]
![back](https://user-images.githubusercontent.com/55958011/66442135-ea6e0a80-ea0f-11e9-9749-541326123ad0.png)
![layout](https://user-images.githubusercontent.com/55958011/66442136-ea6e0a80-ea0f-11e9-88c4-ddbdbb699353.png)
![front](https://user-images.githubusercontent.com/55958011/66442137-ea6e0a80-ea0f-11e9-8dfe-4f051f3f52d4.png)

Atualizção Layout 2

**Comment by DovahKrosis** [comment]
![back](https://user-images.githubusercontent.com/55958011/66445996-16dd5300-ea1f-11e9-9554-ae871e614daf.png)
![layout](https://user-images.githubusercontent.com/55958011/66445997-16dd5300-ea1f-11e9-88a0-9c1120637665.png)
![front](https://user-images.githubusercontent.com/55958011/66445998-16dd5300-ea1f-11e9-854b-f02aa9a3f654.png)

Atualização Layout 3

**Comment by DovahKrosis** [comment]
![front](https://user-images.githubusercontent.com/55958011/66447205-f4016d80-ea23-11e9-9b8d-d9f25c1e8eb2.png)
![Layout](https://user-images.githubusercontent.com/55958011/66447206-f4016d80-ea23-11e9-87e2-552fe5ceefe5.png)
![back](https://user-images.githubusercontent.com/55958011/66447207-f4016d80-ea23-11e9-80da-6c22ac27c7ba.png)

Atualização 4

**Comment by DovahKrosis** [comment]
![front](https://user-images.githubusercontent.com/55958011/66449751-902f7280-ea2c-11e9-8b22-5effa45dd0b0.png)
![Layout](https://user-images.githubusercontent.com/55958011/66449752-902f7280-ea2c-11e9-9091-b9821215b66f.png)
![back](https://user-images.githubusercontent.com/55958011/66449754-90c80900-ea2c-11e9-9f55-b8d80dd6edfd.png)

Atualização 5

**Comment by DovahKrosis** [comment]
![front](https://user-images.githubusercontent.com/55958011/66453168-cd4e3180-ea39-11e9-8916-9e257dfa5538.png)
![back](https://user-images.githubusercontent.com/55958011/66453169-cde6c800-ea39-11e9-896b-d333e2d9a44a.png)
![layout](https://user-images.githubusercontent.com/55958011/66453170-cde6c800-ea39-11e9-8265-e45f91cb1d4c.png)

Modelo Final Layout teclado
