### ISSUE TITLE
Banner

### ISSUE THREAD

**Issue by khayo** [khayo/SMG#5]
Conforme já havia previsto, teremos a necessidade de criação de um banner explicando o o que é e o funcionamento de nosso projeto. Temos na nossa pasta da monografia, aquele inicio de banner, porem precisamos adicionar informações melhores no banner. Enviei aquele manual no telegram recentemente e acredito que ele traga informações muito boas para serem adicionadas no banner. Para fazer o banner usei a ferramenta [Spark Post](https://spark.adobe.com/pt-BR/) da Adobe, que é gratuita e traz diversas ferramentas que facilitam a edição deixando um trabalho bem bonito.

Acho que podemos seguir pela linha de algo mais voltado para o **profissional/comercial** ao invés de adotar uma abordagem acadêmica. Esta tarefa ficará bastante aberta, pois trata-se de desenvolvimento criativo.

Em caso de dúvidas, pergunte por aqui, para que possamos manter o histórico do desenvolvimento

**Informar tempo necessário para desenvolvimento da tarefa.** Lembre-se, que este prazo é para entrega da tarefa **FINALIZADA**, ou seja, após **testes**, **análise** do material entregue e **aprovação** dos membros do grupo, portanto considere estes passos para **definir o prazo** para **finalização da tarefa**

**Comment by khayo** [comment]
![nuvem_tags](https://user-images.githubusercontent.com/4781909/66356037-e5418a80-e93f-11e9-9db1-3211c79c81ba.png)

**Comment by Lucfoxxd** [comment]
Modelo de Banner

**Comment by Lucfoxxd** [comment]
![image](https://user-images.githubusercontent.com/55931764/66356536-a6143900-e941-11e9-9d38-9ad6bfe2f940.png)
Banner Exemplo - 1

**Comment by khayo** [comment]
Ficou definido da seguinte forma a divisão das tarefas do banner:
- Caio
  - Fluxograma simplificado
  - Nuvem de tags
- Gustavo
  - Imagem do display
  - Sensores
- Khayo
  - Lista
  - Características técnicas
  - Código C
  - Proteus
- Lucas
  - Logo
  - Perspectiva de layout frontal

Fazer cada parte individualmente, e enviar para análise antes de iniciar a próxima etapa
**Não importa qual ferramenta será usada** para desenvolver sua parte, o importante é que fique **bem definido o texto** que será usado e as **imagens que serão usadas**. Caso tenha algum bloquei criativo, não exite em procurar por materiais já existentes e **pedir ajuda** para outros membros. Solicite por reunião no **Discord** para **brainstorm**. 
Precisamos acabar esta parte de design o mais rápido o possível, pois a **semana da ETE** é na próxima semana e portanto precisamos disto **o mais rápido o possível**, ainda precisaremos imprimir o banner.

**Comment by khayo** [comment]
Criei as pastas para gente colocar os arquivos organizados, lembrem de dar git pull antes de começar a fazer as tarefas.

@Lucfoxxd - eu havia feito uma prévia de fontes, elas estão no telegram, no canal do tcc, de uma olhada para ter uma base de qual fonte usar, este é o site de onde peguei as fontes: https://fontmeme.com/ (usei como termo de busca, fonte larga).
Sobre Layout frontal, é bom agilizar a issue #1 para que usemos a versão finalizada no banner

@cplds - este site é bem simples para fazer fluxograma, mas se você tiver outro fique a vontade: https://www.draw.io
O site de nuvem de tags que usamos foi este aqui: http://www.abcya.com/word_clouds.htm

@Premone - em relação a foto do display, não sei devemos usar uma foto real do display que dificilmente vai ficar boa ou se devemos usar um print do display do Proteus. O que você acha melhor? 
Sobre os sensor, acredito que o sensor mais "legal" para colocar, seja realmente o sensor de corrente, mas procure uma foto dele pela internet que as fotos que a gente tirou vão estragar o banner.

Conforme forem desenvolvendo, já enviem na pasta para que já iniciemos as analises e montagem do banner

**Lembrando que estamos correndo contra o tempo, precisamos ter esse banner pronto para semana da ETE que será na próxima semana**

**Comment by khayo** [comment]
@Lucfoxxd, não se esqueça de criar o projeto para que você tenha controle do andamento do banner

**Comment by khayo** [comment]
Pessoal, achei esta [ferramenta](https://www.befunky.com) que conta com alguns efeitos grátis bem interessantes, segue algumas imagens que tratei por ele para dar uma coisinha a mais: 

![imagem legal envelhecida 4](https://user-images.githubusercontent.com/4781909/66364999-e71c4580-e961-11e9-9e92-51b05cf13a7a.png)
![imagem legal envelhecida](https://user-images.githubusercontent.com/4781909/66365000-e7b4dc00-e961-11e9-9e8f-ebe5060675f1.png)
![proteus virada](https://user-images.githubusercontent.com/4781909/66365001-e7b4dc00-e961-11e9-8741-9c03231a2705.png)
![proteus](https://user-images.githubusercontent.com/4781909/66365003-e7b4dc00-e961-11e9-96fe-da67ab6ed994.PNG)
![sobreposta proteus](https://user-images.githubusercontent.com/4781909/66365004-e7b4dc00-e961-11e9-877a-bec3b69488e4.png)
![borrada proteus virada](https://user-images.githubusercontent.com/4781909/66365005-e7b4dc00-e961-11e9-8aaa-cc6c93ca260f.png)
![borrada proteus](https://user-images.githubusercontent.com/4781909/66365006-e84d7280-e961-11e9-83f2-4fdb1930a6bc.png)
![imagem legal envelhecida 2](https://user-images.githubusercontent.com/4781909/66365007-e84d7280-e961-11e9-8e4d-e97c6c0fef02.png)
![imagem legal envelhecida 3](https://user-images.githubusercontent.com/4781909/66365008-e84d7280-e961-11e9-8611-c95166a6313e.png)

Provavelmente usarei a imagem que está apenas virada, por estar bem limpa, mas não está aquela coisa "seca"

**Comment by Lucfoxxd** [comment]
Como estou encarregado pela tarefa do layout do módulo para o Banner, medidas reais e ajustes para a parte física do módulo e a logo, então eu me encarrego desta tarefa e já adianto a outra na mesma proporção. 

**Prazo de entrega estimado: 12/10/19 (Sábado) até às 20h**

**Comment by khayo** [comment]
Voltamos a estaca zero com este banner agora que temos que seguir o modelo apresentado pelo professor. Alguém se habilita a fazer esta coisa horrorosa? 

[Modelo Banner Padrão e Definitivo LauroGomes.pptx](https://github.com/khayo/SMG/files/3706904/Modelo.Banner.Padrao.e.Definitivo.LauroGomes.pptx)
![Screenshot_20191008-154659_PowerPoint](https://user-images.githubusercontent.com/4781909/66475097-0b167e80-ea69-11e9-81fb-c9771198de42.jpg)

**Comment by Lucfoxxd** [comment]
Me habilito a fazer essa tarefa.
**Prazo estimado de entrega 12/10/19**

**Comment by khayo** [comment]
Maravilha. Informação adicional obtida pelo grupo da sala (whatsapp) hoje. **O banner deve ter 90cm de altura por 60cm de largura**. Qualquer dificuldade nos comunique para que não fique preso a uma tarefa por muito tempo. Se posso **sugerir**, conforme for fazendo cada  parte vá nos **atualizando com o andamento**, desta forma podemos **otimizar o processo** de analise e revisão.

**Comment by Lucfoxxd** [comment]
Visto.
@khayo

**Comment by Lucfoxxd** [comment]
Vou utilizar alguns dados da Monografia para preenchimento de alguns campos, como, Introdução, Metodologia, Objetivos e Referências. E se tiver muito vago, melhoramos.

**Comment by Lucfoxxd** [comment]
![image](https://user-images.githubusercontent.com/55931764/66705090-ba1cb980-ecf8-11e9-9a63-d5f708a050fb.png)
A **Introdução** falta melhor elaborar o paragrafo introdutório que acrescente no segundo.
**Objetivos** retirados em parte da monografia
Os **Resultados Obtidos** eu fiquei em dúvida e queria que vocês selecionassem as melhores imagens que evidencie um resultado significativo do funcionamento até agora do módulo @khayo, acho que você melhor tem autoridade para mandar essas fotos. (Duas, três)

**Comment by Lucfoxxd** [comment]
![image](https://user-images.githubusercontent.com/55931764/66705123-43cc8700-ecf9-11e9-80d9-9fd355846bf3.png)
A **Metodologia** eu pensei de fazer um fluxograma **por exemplo**: Pesquisa --> Aplicação do conhecimento --> Falha (Sim, não) --> (Não) Tirar dúvida com professores ou pesquisar mais.
As **Referências** eu peguei do nosso projeto principal(monografia), de onde a gente tirou boa parte da teoria.
A **Conclusão ou Considerações Finais** só será feita quando todo o resto estiver feito, revisado, finalizado e aprovado por vocês todos.

**Comment by Lucfoxxd** [comment]
@cplds 
@Premone  
@DovahKrosis

**Comment by Lucfoxxd** [comment]
**Analisem criticamente o que tem até agora, críticas são muito necessárias na escrita de um projeto**
Quando eu chegar verei tudo e concluirei o resto para análise de vocês.

**Comment by khayo** [comment]
"mesmo"?

**Comment by khayo** [comment]
Manda um print da página toda, fica mais fácil de ver

**Comment by Lucfoxxd** [comment]
![image](https://user-images.githubusercontent.com/55931764/66705643-b6d8fc00-ecff-11e9-849e-f64b9af3866b.png)

**Comment by Lucfoxxd** [comment]
Vou alterar esse "mesmo", mania de principiante. Vou melhorar o termo

**Comment by Lucfoxxd** [comment]
Até daqui a pouco.

**Comment by Lucfoxxd** [comment]
![image](https://user-images.githubusercontent.com/55931764/66709542-e4906600-ed3c-11e9-98f4-a3be62f1fded.png)

**Comment by Lucfoxxd** [comment]
Ae galera conforme prometido, eu voltei. Olhem e opinem.

**Comment by DovahKrosis** [comment]
ta laegal, só esse estilo ai q é estranho mas é obrigatório né

**Comment by Lucfoxxd** [comment]
É o jeito. Agr só esperar o cara confeccionar.
