### ISSUE TITLE
Display

### ISSUE THREAD

**Issue by khayo** [khayo/SMG#6]
Com o teclado finalizado (#3) e revisado, agora precisamos colocar o display nesta placa. Algumas **características do display**. 
- 20 pinos
- faremos somente uma ligação simples do display com o teclado e do teclado com a placa principal **(display > teclado > placa principal)**.
- a barra de pinos fica do lado **DIREITO** do display
- o modelo do display é o **ks0108**
- **já existe gnd e Vcc** chegando na placa do teclado, não há necessidade de duplicar este sinal.
- o display conta com um **botão com trava para ligar o led de fundo** e um **trimpot para controle de intensidade** deste mesmo led. Podemos **embutir** estes controles na placa do teclado ou colocar na placa principal. Hoje o trimpot que está sendo usado é do **tipo de precisão**, podemos alterar para o modelo que é mais comumente usado para esta aplicação. Em relação ao botão de ligar o led de fundo, podemos trocar por uma **mini-chave liga/desliga**.

Agora precisamos decidir como vai ser a ligação da placa do teclado com a placa principal. Ou fazemos uma **ligação por cabo**, ou podemos ligar as placas como se a placa do teclado fosse um **cartucho (macho) ligando na placa principal (fêmea)**.  Precisamos levantar os **prós e contras** destes modelos de conexão ou ainda **levantar outras possibilidades** de ligação.

### Em caso de dúvidas, pergunte por aqui, para que possamos manter o histórico do desenvolvimento

**Informar tempo necessário para desenvolvimento da tarefa.** Lembre-se, que este prazo é para entrega da tarefa **FINALIZADA**, ou seja, após **testes**, **análise** do material entregue e **aprovação** dos membros do grupo, portanto considere estes passos para **definir o prazo** para **finalização da tarefa**

**Comment by DovahKrosis** [comment]
EU prefiro uma ligação em cartucho, igual aquele módulo desmontado que você levou um dia, tem que ver o resto do pessoal

**Comment by DovahKrosis** [comment]
"faremos somente uma ligação simples do display com o teclado e do teclado com a placa principal (display > teclado > placa principal)." essa ligação com o teclado eu não entendi.

**Comment by khayo** [comment]
O display vai encaixar na placa do teclado. 
O teclado vai encaixar na placa principal. Só isso

**Comment by DovahKrosis** [comment]
ata blz

**Comment by DovahKrosis** [comment]
tempo necessário para desenvolvimento da tarefa: SÁBADO ÁS 19:00 PM

**Comment by Lucfoxxd** [comment]
Acho que a ligação em cartucho seria mais interessante porque não ficaria separado as duas partes e também ficaria mais fácil integrar os dois componentes.

**Comment by DovahKrosis** [comment]
Lucfoxxd e sobre o botão com trava e o trimpot ?

**Comment by khayo** [comment]
Eu gosto da ideia de cartucho, porém dessa forma, ficaremos com um "quadrado", na verdade um "L", o que dificulta no caso de chegarmos no ponto de criar a "caixa" para o módulo, e até mesmo para colocar o módulo na maleta. Apesar de que, podemos ligar como cartucho e converter para uma ligação de fio caso seja necessário. Levantei mais dúvidas do que soluções. Em resumo, acredito que a melhor solução seja mesmo a ligação "**cartucho**" pela **versatilidade**. 

### O **prazo** para manifestação de opinião vai até **amanha as 15h**, após esse horário vou considerar o debate como **encerrado** e quem não participou como concordou com a maioria. 

@DovahKrosis, adicione a placa, 4 furos para fixação de parafusos. Acredito que 5mm das bordas seja o suficiente e **DIAMETRO** de 3mm.

**Comment by DovahKrosis** [comment]
Vou adicionar os furos, e esperar os comentarios restantes

**Comment by Lucfoxxd** [comment]
@DovahKrosis 
Pode ser usado essa chave liga e desliga. Se usasse o botão ocuparia menos espaço e seria mais viável?

**Comment by Lucfoxxd** [comment]
Então @Khayo. Se utilizasse essa ligação em fio, caso a maleta for em acrílico, daria pra mostrar cada parte do componentes, mas teria fio rondando.

**Comment by khayo** [comment]
A ligação de "cartucho" fica bem flexível, pq nada impede que seja ligado por jumpers tb

**Comment by khayo** [comment]
Você e o @dovahkrosis vão ter que fazer esta parte em conjunto  para que isso funcione

**Comment by Lucfoxxd** [comment]
Nesse caso então definido por cartucho.

**Comment by DovahKrosis** [comment]
pessoal como apareceu ai eu criei **a pasta que conterá layout final da placa "Teclado/Tela"**, os layouts que antecederão a versão final serão colocados aqui, **se poderem opinem sobre** .

**Comment by DovahKrosis** [comment]
![tela_front](https://user-images.githubusercontent.com/55958011/66694950-87d77180-ec90-11e9-8de4-f1f0fcf290a6.png)
![tela_back](https://user-images.githubusercontent.com/55958011/66694951-87d77180-ec90-11e9-9054-7a9771598766.png)
![TELA_LAYOUT](https://user-images.githubusercontent.com/55958011/66694952-88700800-ec90-11e9-97e0-dced44b5c3e2.png)

**V1**

**Comment by DovahKrosis** [comment]
![tela_front](https://user-images.githubusercontent.com/55958011/66695214-40071900-ec95-11e9-8e10-d1ab57b93637.png)
![tela_back](https://user-images.githubusercontent.com/55958011/66695215-40071900-ec95-11e9-8210-22a7cb5aab38.png)
![TELA_LAYOUT](https://user-images.githubusercontent.com/55958011/66695216-409faf80-ec95-11e9-962a-c58b8093acd2.png)

**V2** O que vocês acham ?

**Comment by khayo** [comment]
altere o tamanho da placa para o tamanho de placa que temos disponível (15x10)

**Comment by khayo** [comment]
Alguns pontos para correção.

- Como disse na abertura da Issue, a placa ja possui Vcc e GND, logo **NÃO HÁ NECESSIDADE**  de existir o pino Vcc e GND em **duplicidade**.
- Conferir se os pinos do display estão corretos (KS0108)
- Colocar os nomes dos pinos
- Falta controle de contraste
- Falta chave de liga e desliga do backlight do display

**Comment by khayo** [comment]
![image](https://user-images.githubusercontent.com/4781909/66701274-e8869e80-ecd0-11e9-9dc0-8effe49a9fbe.png)

**Comment by Lucfoxxd** [comment]
Na colocação do Dissipador de calor não vai interferir na montagem né?

**Comment by khayo** [comment]
dissipador?

**Comment by DovahKrosis** [comment]
Confira: 
ENTRADAS DE TENSÃO: **VCC, VO, VEE, LED+.**

ENTRADAS **GND: GND, LED-.**

**O CONTROLE DE LUZ DE FUNDO FAZ NOS PINOS LED+/LED-?**
Eu não tenho o esquema de ligação da tela, mas se isso estiver certo da para fazer.

**Comment by khayo** [comment]
http://embedded-lab.com/blog/lab-20-interfacing-a-ks0108-based-graphics-lcd-part-1/

**Comment by DovahKrosis** [comment]
O prazo de entrega do layout da placa será redefinido quando tivermos as proporções da nova placa de fenolite dupla face.

**Comment by khayo** [comment]
Vou procurar uma empresa de Santo André para fazer o orçamento da placa. Dependendo do valor vou mandar fazer

**Comment by Lucfoxxd** [comment]
OK, avisa nós.

**Comment by khayo** [comment]
Muito caro, R$850. Estou indo na santa Efigênia comprar fenolite dupla face maior pra fazer a placa na mão

**Comment by khayo** [comment]
Tá na mão, vou tentar fazer hj a noite

![20191014_134219](https://user-images.githubusercontent.com/4781909/66768314-af912a00-ee88-11e9-8783-69985b248eb5.jpg)
![20191014_134209](https://user-images.githubusercontent.com/4781909/66768326-b5870b00-ee88-11e9-8218-cfa76a9687f5.jpg)
![Uploading 20191014_134207.jpg…]()

**Comment by Lucfoxxd** [comment]
Tranquilo!
14 out. 2019

**Comment by khayo** [comment]
Estou procurando papel fotográfico para comprar, porém só encontrei papel fotográfico para impressora jato de tinta, acredito que não vai funcionar com este tipo de impressão. Quando conseguir o papel passo novas informações do andamento
