### ISSUE TITLE
Controle de atualização

### ISSUE THREAD

**Issue by khayo** [khayo/SMG#7]
Vou usar esta issue como controle de atualizações, desta forma podemos manter um histórico de fácil leitura das alterações realizada. A partir da próxima postagem, já começarei a listar as mudanças feitas, tentarei linkar ou intercalar a postagem com o commit realizado, não sei se é possível. Fiquem a vontade para tirar dúvidas ou sugerir melhorias.

**Comment by khayo** [comment]
Realizei pequenas alterações no código para que o funcionamento no hardware ficasse dentro do esperado:
- Alteração do cálculo de temperatura
- Correção do posicionamento da exibição dos valores de calibração dos botões
- Travamento dos botões de navegação durante a calibração
- Melhoria na ativação do modo de calibração

**Comment by khayo** [comment]
Ok, é possível referenciar o commit e intercalar com as postagens. Conseguiremos uma boa forma de controle. Estou também criando um projeto para que seja possível definir as tarefas necessárias (TODO)  para continuidade do desenvolvimento.

**Comment by Lucfoxxd** [comment]
Continuo na mesma função desse projeto que você está criando?

**Comment by khayo** [comment]
Você vai gerenciar e me cobrar como combinamos. Este final de semana estipularei os próximos passos a serem executados e pretendo ter um bom avanço para que tenhamos algo concreto para apresentar da semana. Peço a gentileza que não tire o "pinagem" desta Issue para que ela fique sempre na parte de cima da página.

**Comment by khayo** [comment]
Fiz a compra de alguns componentes que prevejo que utilizaremos em brave, entre eles: 
- Conectores DB25 macho e fêmea para PCI e para soldar fios. Acredito que esta será a interface entre nosso simulador e nosso módulo. (_090 L, M, N, O_)
- Barra de pinos fêmea 40 vias, para comunicação da placa principal com teclado (_090 H_) 
- Barra de pinos macho 40 vias 90º para comunicação do teclado com a placa principal (_090 I_)
- Push Button Longo, além de facilitar os testes de protoboard, quando fecharmos o módulo, prevejo que eles serão necessários para que seja possível aperta-los. (_008_).
- Trimpot horizontal de 10, para controle da contraste do display, que será colocar na placa do teclado, caso seja definido que o trimpot ficará na placa do teclado. (_203B_)
- Separei do estoque a chave de liga e desliga para o led de fundo do display (_133_)

Em relação a parte lógica, não fiz nenhum progresso, pois com a chegada dos componentes, gastei um tempo adicionando os itens ao sistema.
Algumas fotos dos componentes e dos botões longos instalados na protoboard.
![20191011_000809](https://user-images.githubusercontent.com/4781909/66622819-90ac4280-ebbf-11e9-9351-8cceac43cef7.jpg)
![20191011_001929](https://user-images.githubusercontent.com/4781909/66622820-90ac4280-ebbf-11e9-9fe5-44a84d0aec2e.jpg)
![20191011_001952](https://user-images.githubusercontent.com/4781909/66622821-9144d900-ebbf-11e9-8cee-43bdcf620a6b.jpg)
![20191011_002025](https://user-images.githubusercontent.com/4781909/66622822-9144d900-ebbf-11e9-9a64-f46fc5de36d0.jpg)
![20191011_002054](https://user-images.githubusercontent.com/4781909/66622823-9144d900-ebbf-11e9-9bf0-ab34c22c8b6b.jpg)
![20191011_002058](https://user-images.githubusercontent.com/4781909/66622816-90ac4280-ebbf-11e9-8e04-e467a82cf9b1.jpg)

**Comment by DovahKrosis** [comment]
muito legal esses push buttons altos

**Comment by khayo** [comment]
Identifiquei quais são as rotinas prioritárias para o desenvolvimento do módulo e as coloquei no projeto "desenvolvimento principal".

Também fiz um levantamento das portas que estão sendo usadas e de quais portas estão disponíveis, e felizmente teremos portas o suficiente para continuar o desenvolvimento sem a preocupação de necessitar de mais portas (digitais e analógicas).

Estava fazendo algumas verificações no hardware e aconteceu algo estranho, o processamento estava acontecendo extremamente lento, isto nunca havia acontecido e fiz uma pequena revisão nas ligações e identifiquei uma conexão de fios positivos e negativos que não estavam muito bem encaixados. recoloquei os cabos e parece que está ok agora. Durante esta verificação notei que o LM35 foi ligado de maneira incorreta. Ainda não fiz a ligação correta, porem acredito que este seja o motivo da temperatura não estabilizar no display e também de existir divergências nos cálculos que deveriam ser feitos e os cálculos que estão sendo feitos. 

Farei a correção do circuito e farei algumas alterações de portas usadas para que fiquem disponíveis portas analógicas para alguma eventualidade.

**Comment by khayo** [comment]
Durante a revisão do projeto, notei que o cálculos que fiz para o divisor de tensão do sensor de tensão VCC estavam errados, na verdade estavam para o valor de 20v. Refiz os cálculos e alterei o divisor de tensão

**Comment by khayo** [comment]
Finalizei a revisão da protoboard. 

- Refeita ligações dos reles já instalado
- Feita ligação dos reles que não estavam instalados
- Correção das ligações do sensor de temperatura
- Correção dos cálculos e circuitos do divisor de tensão
Esta é a protoboard agora
![20191012_004940](https://user-images.githubusercontent.com/4781909/66694534-d6820d00-ec8a-11e9-89ba-ca37e9a34c8d.jpg)

Na primeira ligação houve um problema de funcionamento devido a ligação invertida do lm35. Aparentemente não houve dano aos componentes.

**Comment by khayo** [comment]
Notei que após o módulo ficar parado em uma tela por um determinado tempo, os botões de navegação param de funcionar corretamente. imagino que seja algum tipo de excesso de processamento. Vou tentar descobrir o que está ocasionando a falha, após implementar algumas funções indispensáveis para a demonstração

**Comment by khayo** [comment]
Após o envio do código sem comunicação serial, houve uma melhora no desempenho e o sistema parou de travar. Para o propósito do TCC, deixaremos esta função desativada.

**Comment by khayo** [comment]
Atual disposição das portas:

2   - Sensor de temperatura (AN0/RA0)
3   - Botões (AN1/RA1)
4   - Sensor de tensão continua (AN2/AN2)
5   - Rele - Pre-aquecimento (RA3/AN3)
6   - Rele - Solenoide (RA4)
7   - Rele - Motor de pártida (RA5/AN4)
8   - Rele - Gerador (RE0)
9   - Rele - Rede (RE1)
10  - Livre (RE2/AN7)
15  - Livre (RC0)
16  - Livre (RC1)
17  - Emergência (RC2)
23  - Livre (RC4)
24  - Livre (RC5)
25  - TX
26  - RX

**Comment by Lucfoxxd** [comment]
Muito bom
Tem bastante informação pertinente para adicionar à monografia.

**Comment by khayo** [comment]
Estou fazendo teste nos reles, configurei os botões reset, manual e automático, para acionar os reles pre-aquecimento, solenoide e motor de partida. Os reles solenoide e motos de partida estão funcionando como o esperado, porém o rele de pre-aquecimento está desligando ao acionar o rele de motor de partida e solenoide. A falha não se repete ao acionar o rele de rede ou de gerador. Vou verificar as ligações físicas, pois não vejo acredito que seja possível que seja uma fala de programação devido a simplicidade do código  (PRE_AQUEC = !PRE_AQUEC;)

**Comment by khayo** [comment]
Outra informação importante é que o botão que liga o rele do pre-aquecimento não consegue desligar o pre-aquecimento

**Comment by khayo** [comment]
Descobri o erro, o registrador ADCON1 estava configurado para portas analógicas de AN0 até AN3. Como fiz as alterações nas portas, a porta RA3 estava configurada como analógica, quando deveria ser digital. Fiz as alterações e está funcionando como esperado.

**Comment by khayo** [comment]
O funcionamento "básico" do módulo está finalizado. Agora vem a parte de monitoramento de energia, que farei pelo Arduíno.

**Comment by khayo** [comment]
Realizei alguns testes nos circuitos do projeto que estavam a algum tempo parados (gerador de função e comunicação serial) para verificar se estavam funcionando corretamente e está tudo funcionando como esperado. A partir de segunda me dedicarei a leitura de tensão, corrente e frequência de rede, espero no próximo final de semana trazer resultados concretos sobre o desenvolvimento desta parta.

**Comment by khayo** [comment]
Durante o dia estive pensando nos materiais que teremos que comprar. Da parte de eletrônica, acredito que não tenha mais nenhum material para comprar, mas para a parte de elétrica, teremos que providenciar algumas coisas. 
- [Contatoras WEG CAW04](https://produto.mercadolivre.com.br/MLB-1225736458-minicontator-weg-cawm4-40-00v26-220v-60hz-10045381-_JM?quantity=1#position=4&type=item&tracking_id=6438d111-f7c7-40b2-a4fb-f28d1616f09c) (3 unidades).  (aquelas eram da AGESP, não podemos contar com elas)
- [Base Soquete para Rele](https://produto.mercadolivre.com.br/MLB-1220465906-base-soquete-porta-rele-5-4-pinos-40-amp-montavel-_JM?matt_tool=86155663&matt_word&gclid=CjwKCAjwxaXtBRBbEiwAPqPxcKKuIsKEv-gZl0FsftUpb0TZVVVizZJa-NqvmAYZvnsvVSa4iq6T4RoCRgoQAvD_BwE&quantity=1) (2 unidades)
- [Reles Automotivos](https://produto.mercadolivre.com.br/MLB-769337686-rel-auxiliar-automotivo-universal-12v-3040a-5-pinos-preto-_JM?quantity=1#position=1&type=item&tracking_id=08c258dc-c414-4f21-945f-d73d6c1a0dd3) (2 unidades)
- Acrílico, acredito que o @DovahKrosis consiga pra gente

Hoje comprei uma peça para consertar minha impressora a laser, as peças devem chegar no meio da semana que vem, assim posso trabalhar com as PCI mais tranquilamente e sem a preocupação de ocorrer alguma falha no processo de impressão, perdendo o dia de trabalho.
O papel fotográfico estou estudando qual traz um melhor resultado, encontrei dois lugares que recomendaram o [Papel Fotográfico Epson 95g High Quality Inkjet S041117 100Fls](https://www.kalunga.com.br/prod/papel-especial-95g-high-quality-inkjet-fosco-s041117-epson/478693?pcID=39&gclid=CjwKCAjwxaXtBRBbEiwAPqPxcK96P5AgAGq9B4VS_8_CRKWmBVHbFyhZBoCn1FRku-DI7MUy0dvrZhoCZzMQAvD_BwE). Pretendo comprar amanhã durante o dia. 

Vi um vídeo ensinando como criar protocolos de comunicação, achei bem interessante e relativamente simples, se tivéssemos mais tempo, seria bem legal desenvolver um protocolo próprio, não por necessidade, mas pelo aprendizado. Então, continuamos com a comunicação serial mesmo, vou dar uma revisada no código do protótipo de comunicação e tentar fazer a comunicação propriamente dita.

**Comment by khayo** [comment]
Ontem chegaram as peças da impressora laser que precisava ser arrumada. Troquei as peças e apanhei o dia todo dos drivers da impressora, mas finalmente deixei funcionando decentemente. Algumas fotos dos resultados:

![20191020_155534](https://user-images.githubusercontent.com/4781909/67167309-b62f0e00-f36e-11e9-9ce5-2c64eacc2c91.jpg)

![20191020_163614](https://user-images.githubusercontent.com/4781909/67167321-d8c12700-f36e-11e9-801a-cba6f883a9b1.jpg)

![20191020_163622](https://user-images.githubusercontent.com/4781909/67167326-dbbc1780-f36e-11e9-8909-54dc0a8b69b9.jpg)

![20191020_165853](https://user-images.githubusercontent.com/4781909/67167327-dd85db00-f36e-11e9-83df-3bebf375fcf8.jpg)

Próximo passo é comprar o papel fotográfico, farei isto semana que vem, estou duro.

**Comment by khayo** [comment]
O GitHub decidiu que vai colocar a foto de cabeça pra baixo, vai entender..

**Comment by khayo** [comment]
Conversei com o Plez ontem, temos até o fim do mês de novembro para apresentar, podemos apresentar antes, o que provavelmente é uma ótima ideia, vou acelerar o desenvolvimento. FAÇAM ALGUMA COISA.

**Comment by khayo** [comment]
Para melhorias futuras

https://youtu.be/oi3PKpMxIF8

**Comment by khayo** [comment]
Comprei o papel para fazer as placas, vou revisar o layout e fazer os primeiros testes.
![20191026_174508](https://user-images.githubusercontent.com/4781909/67626907-998c4d80-f828-11e9-95f2-408968be8993.jpg)

**Comment by khayo** [comment]
Fiz a primeira placa pelo processo de transferência, os resultados não foram dos melhores, mas deu pra entender os pontos que precisam ser melhorados. Se usar o ferro frio, não transfere, muito quente corre o risco de danificar a placa. Além disso, mesmo com a placa dando errado, notei que seria bom aumentar o tamanho das trilhas, elas não ficaram ruins, mas alguns pontos poderiam não ter dado certo e se na placa for necessário fazer algum acerto com caneta antes da corrosão, com a trilha mais larga ficará mais fácil.  
Notei tb que fazer cada lado individualmente provavelmente não vai dar certo. Agora como fazer as duas ao mesmo tempo vai ser um desafio, ainda estou pensando em uma solução. 

No geral as ilhas ficaram muito boas, exceto algumas trilhas dos botões, mas nada que fosse impossibilitar o uso da placa. 

Acredito que durante a semana eu consigo fazer a placa. 
Algumas fotos de como ficou. 
![20191027_200948](https://user-images.githubusercontent.com/4781909/67646105-37584900-f90b-11e9-98a2-118b8d955407.jpg)
![20191027_200953](https://user-images.githubusercontent.com/4781909/67646106-37584900-f90b-11e9-81c0-fa20b1fa1d27.jpg)
![20191027_201109](https://user-images.githubusercontent.com/4781909/67646107-37f0df80-f90b-11e9-8d5f-d6577d31cc11.jpg)
![20191027_201112](https://user-images.githubusercontent.com/4781909/67646108-37f0df80-f90b-11e9-9b42-527122237315.jpg)





![20191027_201119](https://user-images.githubusercontent.com/4781909/67646101-36bfb280-f90b-11e9-8734-80774ebc256a.jpg)
![20191027_183436](https://user-images.githubusercontent.com/4781909/67646102-37584900-f90b-11e9-9183-c0ae54b9846b.jpg)
![20191027_193603](https://user-images.githubusercontent.com/4781909/67646103-37584900-f90b-11e9-85dd-76c3ecdea9c3.jpg)
![20191027_200946](https://user-images.githubusercontent.com/4781909/67646104-37584900-f90b-11e9-8874-b1b1b5451a6c.jpg)

**Comment by khayo** [comment]
Fiquei pensando em como fazer para transferir os dois lado de uma vez, e pensei no furo guia, já tinha antes mas acabou sumindo por algum motivo, e agora tem de novo. Além disso coloquei um jumper  no trimpot de contraste, achei que assim ficaria melhor para soldar na barra de pinos.

**Comment by DovahKrosis** [comment]
ou na placa ta escrito Janeiro 2017, não é 2018 ???

**Comment by khayo** [comment]
> ou na placa ta escrito Janeiro 2017, não é 2018 ???

Fiz a alteração conforme o commit 5fe8169. Iniciei o processo de manufatura da placa, hj corte e limpei. Pretendo amanhã fazer as trilhas e corroer.
