### ISSUE TITLE
Apresentação na semana da ETE

### ISSUE THREAD

**Issue by Lucfoxxd** [khayo/SMG#9]
Temos algumas especificações para a apresentação do projeto na semana da ETE que será realizada no dia 16/10/19, quarta-feira:

1. O banner será apresentado na direção junto com uma apresentação referente ao projeto, onde os professores vão dar a nota numa ficha que deveremos imprimir, preencher a nossa parte e levar para eles preencherem o resto.

2. Será necessários pelos menos duas ou três pessoas na direção para apresentação aos professores **segundo o Fialho**. As pessoas que não estiverem na diretoria, estarão no bloco 5 explicando o projeto, eu **sugiro imprimir algumas fichas que fizemos referentes ao projeto para nortear a apresentação** quem for ficar na sala do bloco 5 para entregar as pessoas.

3. Salas em que vão ficar no bloco 5 e os professores que vão avaliar, se informar qual das salas vão ficar, segue a imagem:
![image](https://user-images.githubusercontent.com/55931764/66792133-c5750e00-eecd-11e9-9cbd-e4c628f7b81d.png)

4. Cada grupo tem que receber no mínimo três avaliações de três professores onde essa ficha será passada ao orientador que é o Plez.

5. Devemos imprimir 3 conjuntos dessas fichas **segundo informações passadas pelo Whatsapp** para que os professores possam gerar a notas.
Segue as folhas da ficha:

**Folha 1**
![Slide1](https://user-images.githubusercontent.com/55931764/66792355-a3c85680-eece-11e9-8879-d20c59512f17.JPG)

**Folha 2**
![Slide2](https://user-images.githubusercontent.com/55931764/66792370-b773bd00-eece-11e9-9e13-42ce841f82c4.JPG)

**Folha 3**
![Slide3](https://user-images.githubusercontent.com/55931764/66792382-c490ac00-eece-11e9-8689-0710047aecd4.JPG)

6. A tarefa atribuída será definir **quem irá ficar no bloco 5 e os temas que serão divididos para apresentar aos professores tanto na diretoria quanto no bloco 5**, pois se  todos tiverem que apresentar juntos por algum problema, todos sabem o conteúdo/falas e o que está acontecendo exatamente em ambos os locais da apresentação. 

**7. Como o prazo está super apertado, a urgência é definir tudo até amanhã o mais cedo possível para ter tempo de ensaiar a apresentação e evitar erros desnecessários.**

**Comment by khayo** [comment]
Por mim tanto faz, eu to tranquilo quanto a apresentação, pode me mandar onde for mais complicado

**Comment by Lucfoxxd** [comment]
Tudo bem então. Vou separar.

**Comment by Lucfoxxd** [comment]
Fica eu, Khayo e mais uma pessoa para apresentar na banca para os professores.
O Guilherme sugeriu a seguinte: 
Lucas, Khayo e Gustavo para os professores.
Caio e Guilherme lá na diretoria.
Eu concordo com essa divisão.

Sobre as questões que foram apresentadas ontem, a dúvida de apresentar todo mundo junto ou não é uma possibilidade de acontecer.

Vou dividir os seguintes temas que ficará tanto pras três pessoas quanto para as duas (tentar apresentar em pelo menos 15 minutos pra não ficar cansativo):

1 INTRODUÇÃO
2 OBJETIVOS
3 METODOLOGIA
4 PROBLEMAS RESOLVIDOS, ENCONTRADOS E DIFICULDADES EM EXECUTAR O PROJETO ATÉ O MOMENTO
5 RESULTADOS OBTIDOS ATÉ AGORA
6 CONCLUSÃO

(A divisão é simples o 6 é múltiplo de 3 e de 2 então os membros ficarão com as mesmas quantidades tanto em um bloco, quanto no outro se ocorrer isso mesmo)

**O que eu preciso de vocês agora é:** 
- Quem vai imprimir uma ficha e preencher, e imprimir pelo menos uns 3 panfletos daqueles que foram feitos pelo Khayo.
- E preciso que dividam o que cada um irá falar (tanto as duas pessoas, quanto as 3), para já treinar a apresentação. (Escolham seus temas)
- E preciso também da divisão caso se todos fossem apresentar juntos. (Escolha seu tema, nesse caso, uma pessoa irá ficar com dois temas)

**Os professores irão tirar dúvidas, então quaisquer dúvidas sobre o projeto até aqui, é bom tirar o quanto antes no grupo do Telegram ou aqui mesmo na Issue**

Temos a Monografia, o arquivo do Alterações Pendentes e o Banner para se basear em conteúdo.

**Comment by Lucfoxxd** [comment]
Temas Lucas para 3 pessoas: Introdução e Conclusão. 
Temas Lucas para 5 pessoas: Introdução

**Façam nesse modelo**

Eu já separei os meus. Se precisar mudar, nós mudamos sem problema.

**Comment by GustavoOliveiraBarros** [comment]
Eu fico com metodologia e objetivos
